"use client"; // Ensure Material-UI works on the client-side
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import "@fontsource/great-vibes";
import Navbar2 from "@/components/Navbar2";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        {pathname === "/" ? (
          
            <Navbar />
          
        ) : (
          <Navbar2 />
        )}

        {children}
      <Footer/>
      </body>
    </html>
  );
}
